<a href="https://colab.research.google.com/github/sense64/data_viz/blob/main/prg_random01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.random.rand(10) #10개의 난수가 생성

b = np.random.rand(2,5) #2행 3열 행렬의 난수가 생성

print('a 배열=' , a)
print()
print('b 차원 행렬=', b)

a 배열= [0.17341776 0.78141755 0.97989054 0.26963144 0.43340837 0.88881903
 0.73807928 0.20840501 0.02749714 0.29743734]

b 차원 행렬= [[0.73589392 0.40248276 0.52947058 0.21198859 0.30206966]
 [0.02352329 0.15807834 0.01229746 0.56658898 0.91589626]]


In [8]:
#정수형 난수를 발생

c = np.random.randint(5, size=10)

print(c)

d = np.random.randint(10, 100, size=10)

print(d)

e = np.random.randint(10, 200, size=(2,5)) # 2by5으 행렬의 정수형 난수가 생성

print(e)

[2 1 4 3 4 2 1 4 1 1]
[92 26 73 95 31 45 66 23 71 35]
[[118  57 147 116 157]
 [ 50 190  42 127 157]]


In [ ]:
#표준정규분포에서 난수를 발생

In [11]:
n1 = np.random.randn(5)
print(n1)

n2 = np.random.randn(2,3)
print(n2)

sigma = 2.0
mu = 3.0

n3= sigma*np.random.randn(3) + mu
print(n3)

[-1.16650914 -0.08304188  0.86148563 -1.64272858 -0.07804904]
[[ 1.19184879 -2.89049631 -0.87870903]
 [ 0.48385494 -1.00602964  1.04399596]]
[4.67400762 4.05436618 0.76961787]


In [12]:
# 정규분포로 분터 샘플링 된 데이터 중 난수 생성

n1= np.random.normal(0, 1, size= 3)
print(n1)

n2 = np.random.normal(2, 2, size= 4)
print(n2)

n3 = np.random.normal(2.0, 3.0, size= (3, 4))
print(n3)

[-0.13287315 -1.97499088 -0.88297449]
[0.17765674 1.04687392 1.95507881 5.04471722]
[[ 5.69694884  3.07369998  1.01569289  1.27834132]
 [-0.15576719  8.09824191  2.90593026 -2.69169136]
 [ 2.1641227  -0.13137062 -1.27956507 -1.6754633 ]]


In [14]:
data = [20, 15, 18, 30, 11, 45, 80, 13, 77, 54, 30]

a = np.random.choice(data, 4)
print(a)

[54 30 54 80]


In [11]:
a = np.random.rand(4)
print("a=", a)


a= [0.44130922 0.15830987 0.87993703 0.27408646]


In [13]:
np.random.seed(5) #시드값 부여
c = np.random.rand(4)
print("c=", c)

c= [0.22199317 0.87073231 0.20671916 0.91861091]
